name: Create Release with Dependencies

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          extensions: mbstring, xml

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create plugin package with dependencies
        run: |
          PLUGIN_NAME="gravity-forms-validator"
          VERSION=${GITHUB_REF#refs/tags/v}
          ZIP_NAME="${PLUGIN_NAME}-${VERSION}-with-dependencies.zip"
          
          # Create a temporary directory with the correct plugin name
          mkdir -p /tmp/${PLUGIN_NAME}
          
          # Copy all files to the temporary directory, excluding unwanted files
          rsync -a --exclude=".git" --exclude=".github" --exclude=".gitignore" \
                   --exclude=".vscode" --exclude=".idea" --exclude="*.zip" \
                   . /tmp/${PLUGIN_NAME}/
          
          # Create zip from the temporary directory
          cd /tmp
          zip -r $GITHUB_WORKSPACE/$ZIP_NAME ${PLUGIN_NAME}
          cd $GITHUB_WORKSPACE
      
      - name: Create standard plugin package (without vendor)
        run: |
          PLUGIN_NAME="gravity-forms-validator"
          VERSION=${GITHUB_REF#refs/tags/v}
          ZIP_NAME="${PLUGIN_NAME}-${VERSION}.zip"
          
          # Create a temporary directory with the correct plugin name
          mkdir -p /tmp/${PLUGIN_NAME}-no-vendor
          
          # Copy all files to the temporary directory, excluding unwanted files
          rsync -a --exclude=".git" --exclude=".github" --exclude=".gitignore" \
                   --exclude=".vscode" --exclude=".idea" --exclude="*.zip" \
                   --exclude="vendor" \
                   . /tmp/${PLUGIN_NAME}-no-vendor/
          
          # Create zip from the temporary directory with the correct folder name
          cd /tmp
          mkdir -p ${PLUGIN_NAME}
          cp -r ${PLUGIN_NAME}-no-vendor/* ${PLUGIN_NAME}/
          zip -r $GITHUB_WORKSPACE/$ZIP_NAME ${PLUGIN_NAME}
          cd $GITHUB_WORKSPACE
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gravity-forms-validator-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
